version: "3.8"

services:
  database:
    image: postgres:16.1
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env.prod
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  api:
    build:
      dockerfile: Dockerfile.prod
    working_dir: /homecontrol-api
    # Doesn't work on Windows - so still cant use mDNS for Hue Bridges
    # network_mode: "host"
    restart: always
    ports:
      - "8000:8000"
