version: "3.8"

services:
  database:
    image: postgres:16.1
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env.prod
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  api:
    build:
      dockerfile: Dockerfile.prod
    working_dir: /homecontrol-api
    # Required for mDNS discovery (Won't work on Windows/WSL)
    network_mode: "host"
    restart: always
    # ports:
    #   - "8000:8000"
