version: "3.8"

services:
  api:
    build: .
    working_dir: /homecontrol
    command: "uvicorn homecontrol_api.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./:/homecontrol
    ports:
      - "8000:8000"
