version: "3.8"

services:
  api:
    build: .
    working_dir: /homecontrol-api
    volumes:
      - ./:/homecontrol-api
    # Doesn't work on Windows - so still cant use mDNS for Hue Bridges
    # network_mode: "host"
    ports:
      - "8000:8000"
